project_id = "dhznyjtisfdxzbnzinab"

[functions.external-quote-api]
verify_jwt = false

[functions.api-v1-etiquetas]
verify_jwt = false

[functions.company-branch-webhook-dispatch]
verify_jwt = false

[functions.webhook-dispatch]
verify_jwt = false

[functions.webhook-tms]  
verify_jwt = false

[functions.create-asaas-payment]
verify_jwt = false

[functions.check-asaas-status]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.send-custom-email]
verify_jwt = false

[functions.motorista-operations]
verify_jwt = false

[functions.shipment-webhook-dispatch]
verify_jwt = false

[functions.cte-webhook]
verify_jwt = false

[functions.auto-webhook-dispatcher]
verify_jwt = false

[functions.auto-label-dispatch]
verify_jwt = false

[functions.test-webhook-url]
verify_jwt = false

[functions.secure-tracking]
verify_jwt = false

[functions.carrier-label-webhook]
verify_jwt = false

[functions.validate-b2b-pricing]
verify_jwt = false
