project_id = "dhznyjtisfdxzbnzinab"

[functions.webhook-dispatch]
verify_jwt = false

[functions.webhook-tms]  
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false